### ISSUE TITLE
윤창일 연구노트

### ISSUE THREAD

**Issue by shanmdphd** [pipetcpt/interns#1]
@funnysharky 선생님,

연구(공부)하며 배운 것을 댓글로 기록합니다.

예시)

![image](https://user-images.githubusercontent.com/6946821/61848238-6d3ef900-aee8-11e9-9e16-94065f1207ae.png)

**Comment by shanmdphd** [comment]
@funnysharky 오늘 만나서 반가웠습니다. 곧 3학년이네요. 이제 실습 나가나요? Good luck!

**Comment by funnysharky** [comment]
@shanmdphd 오랜만에 인사드립니다 교수님 ㅎㅎㅎ 네 2달 후면 실습돌러 갑니다  드디어!^ㅁ^
